# Generated by Django 4.0 on 2022-05-09 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_fresh'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
        migrations.DeleteModel(
            name='Fresh',
        ),
    ]
